# Google Analytics
google_analytics: UA-136144992-1

#visit_count(Powered by busuanzi on http://busuanzi.ibruce.info/)
visit_count: true

paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-octicons

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"